version: '3'

services:
  jekyll:
    container_name: jekyll
    build:
      context: .
    image: dceoy/jekyll:latest
    volumes:
      - ${PWD}:/work
    working_dir: /work
    ports:
      - 4000:4000
    entrypoint:
      - /usr/local/bundle/bin/jekyll
    command:
      - serve
      - --host=0.0.0.0
      - --drafts
      - --watch
